### ISSUE TITLE
[Request] Plug-in and mod only pack

### ISSUE THREAD

**Issue by wad8989** [ManlyMarco/RG-HF_Patch#1]
Is there any chance that there will be a pack that only including plug-in and mod for RG and KKS? 

The file size will be greatly reduced, so that it would be good for players like me that only want the "features" but are not really interested in the additional items.

Please consider it?

**Comment by ManlyMarco** [comment]
The issue is that new users absolutely **will** get that version despite warnings and then clog help channels. In RG there's so little plugin updates I don't think it's worth it, honestly. It's easy to keep up with the mod release channel on the discord server.
